
name: npm publish

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://registry.npmjs.org/
        cache: 'yarn'

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - uses: supplypike/setup-bin@v3
      with:
        uri: 'https://github.com/calcit-lang/calcit/releases/download/0.7.0-a7/cr'
        name: 'cr'
        version: '0.7.0-a7'

    - uses: supplypike/setup-bin@v3
      with:
        uri: 'https://github.com/calcit-lang/calcit/releases/download/0.7.0-a7/caps'
        name: 'caps'
        version: '0.7.0-a7'

    - name: "compiles to js"
      run: >
        caps --ci && cr --emit-js --once
        && yarn && yarn vite build --base=./

    - name: Deploy to server
      id: deploy
      uses: Pendect/action-rsyncer@v2.0.0
      env:
        DEPLOY_KEY: ${{secrets.rsync_private_key}}
      with:
        flags: '-avzr --progress'
        options: ''
        ssh_options: ''
        src: 'dist/*'
        dest: 'rsync-user@tiye.me:/web-assets/repo/${{ github.repository }}'

    - name: "compiles to js"
      run: >
        rm -rf dist/*
        && yarn compile-cli

    - name: Display status from deploy
      run: echo "${{ steps.deploy.outputs.status }}"

    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
